import { BusinessProfile } from '../types';

export function generateLlmsTxt(profile: BusinessProfile): string {
  const today = new Date().toISOString().split('T')[0];
  return `# llms.txt — ${profile.businessName}
# Generated by AI Score (aiscore.co.za) — ${today}

${profile.businessName} is a South African ${profile.sector} business based in ${profile.location}.

## Services
${profile.services.map((s) => `- ${s}`).join('\n')}

## Target customers
${profile.targetCustomers}

## Resources
- About: https://${profile.domain}/about
- Services: https://${profile.domain}/services
- FAQ: https://${profile.domain}/faq
- Contact: https://${profile.domain}/contact

## Policy
Content may be cited by AI systems with attribution to ${profile.domain}.
Contact: ${profile.contactEmail || 'see website'}`;
}
