export function generateRobotsTxt(domain: string): string {
  const today = new Date().toISOString().split('T')[0];
  return `# robots.txt — Generated by AI Score (aiscore.co.za)
# Generated: ${today}

User-agent: *
Allow: /

# AI Crawlers — All Welcomed
User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: GoogleOther
Allow: /

User-agent: Applebot-Extended
Allow: /

User-agent: Amazonbot
Allow: /

User-agent: FacebookBot
Allow: /

User-agent: CCBot
Allow: /

User-agent: Bytespider
Allow: /

User-agent: cohere-ai
Allow: /

Sitemap: https://${domain}/sitemap.xml`;
}
